CRDCDH-1782 Add Test MDF
CBIIT/crdc-datahub-models pull request #146
Opened 2024-10-10 17:41 UTC by amattu2

### Overview

This PR adds the Test MDF to our CRDC-DH repo.

### Change Details (Specifics)

- Add the single YML file from https://github.com/CBIIT/bento-mdf/blob/main/python/tests/samples/crdc_datahub_mdf.yml
- FE/BE do not support a single YAML file ATM, so the mdf file is referenced twice for the `model-file` and `prop-file` fields
- No loading files were provided, we can add it later

### Related Ticket(s)

CRDCDH-1695

2024-10-10 17:44 UTC, amattu2 commented on cache/content.json
> +          "md5-field": ""
I didn't see an obvious md5-field property, so I left it blank.

2024-10-10 17:44 UTC, amattu2 commented on cache/content.json
> +          "name-field": "",
Same for this. Unsure which property it would be

2024-10-10 17:45 UTC, amattu2 commented on cache/content.json
> +      "main-nodes": {
I removed the PI semantic as I don't see one in the model. I might have missed it though.

2024-10-10 20:06 UTC, n2iw requested changes

2024-10-10 20:06 UTC, n2iw commented on cache/content.json
> +        "program": "Program",
program should be removed also, I don't see it in the model.

2024-10-10 20:06 UTC, n2iw commented on cache/content.json
> +        "subject": "Participant",
"subject" should be "participant"

2024-10-10 20:06 UTC, n2iw commented on cache/content.json
> +        "specimen": "Sample",
"specimen" should be "sample"

2024-10-10 20:06 UTC, n2iw commented on cache/content.json
> +        "data_file": "File"
"data_file" should be "file"

2024-10-10 20:06 UTC, n2iw commented on cache/content.json
> +        "data_file": {
"data_file" should be "file"

2024-10-10 20:06 UTC, n2iw commented on cache/content.json
> +          "name-field": "",
I'll ask Nelson to add missing properties.

2024-10-10 21:16 UTC, amattu2 commented on cache/content.json
> +        "data_file": {
Updated in b9e57f7

2024-10-10 21:17 UTC, amattu2 commented on cache/content.json
> +        "data_file": "File"
Updated in b9e57f7

2024-10-10 21:17 UTC, amattu2 commented on cache/content.json
> +        "specimen": "Sample",
Updated in b9e57f7

2024-10-10 21:17 UTC, amattu2 commented on cache/content.json
> +        "subject": "Participant",
Updated in b9e57f7

2024-10-10 21:17 UTC, amattu2 commented on cache/content.json
> +        "program": "Program",
Removed in b9e57f7

2024-10-21 20:11 UTC, amattu2 commented on cache/content.json
> +          "name-field": "",
Updated MDF and defined the name/md5 fields in the content config.

2024-10-21 20:20 UTC, n2iw approved these changes
LGTM

2024-10-21 20:20 UTC, merged